version: '3'

services:
  app:
    # Using a Dockerfile is optional, but included for completeness.
    build: 
      context: .
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      args: 
        VARIANT: buster

    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached
      - test:/test

    command: /bin/sh -c "while sleep 1000; do :; done"  
  another-service:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017

volumes:
  test: